AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS LAmbda Function to Validate US Address

Resources:
  CreditCardAuthorize:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Environment:
        Variables:
          BETA_URL: "apitest.authorize.net"
          PROD_URL: "api.authorize.net"
          PORT: "443"
          GATEWAY_LOGIN: GATEWAY_LOGIN
          GATEWAY_KEY: GATEWAY_KEY
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
